# Generated by Django 3.1 on 2020-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('current_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
    ]
